# Generated by Django 3.0.6 on 2020-05-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm_inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('money', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Storm_data',
        ),
    ]
