# Generated by Django 3.0.6 on 2020-05-13 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm_inv', '0002_auto_20200512_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snacks',
            new_name='Snack',
        ),
    ]
