# Generated by Django 3.0.6 on 2020-05-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm_inv', '0003_auto_20200512_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='fname',
        ),
    ]
