# Generated by Django 3.0.6 on 2020-05-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm_inv', '0004_auto_20200513_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='fname',
            new_name='name',
        ),
    ]
