# Generated by Django 3.0.6 on 2020-05-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm_inv', '0007_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.AlterField(
            model_name='person',
            name='money',
            field=models.FloatField(null=True),
        ),
    ]
