# Generated by Django 3.0.6 on 2020-05-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm_inv', '0008_auto_20200515_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='movement',
            field=models.TextField(null=True),
        ),
    ]
